name: Cosign Image on Push
on: [push]

jobs:
  sign-and-verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write 

    env:
      REPO_NAME:
      IMAGE_TAG: 1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.5.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.$IMAGE_TAG }}

      - name: Sign the published Docker image
        run: |
          cosign sign --yes ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:${{ env.$IMAGE_TAG }}

      - name: Output image tags
        env:
          TAGS: ${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}
        run: |
          echo "## Built images with the following tags" >>$GITHUB_STEP_SUMMARY
          echo "${TAGS}" >>$GITHUB_STEP_SUMMARY
